server:
  datasources:
    default:
      jdbc-url: "jdbc:h2:mem:jdbi"
      username: "username"
      password: ""
      log-query-execution-longer-than-ms: 0
      log-stacktrace-for-long-query-execution: false
